{
 "title": "Containers (cAdvisor)",
 "tags": [ "cadvisor" ],
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(container_cpu_usage_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 container CPU (cores/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_usage_seconds_total{instance=~\"$instance\", image!=\"\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 container Memory (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "topk(10, container_memory_working_set_bytes{instance=~\"$instance\", image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 container Network RX (bytes/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "topk(10, rate(container_network_receive_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}