#!/bin/bash
set -euo pipefail

cd ~/byz-fed-ids-5g

RUN_DIR=$(ls -dt "$HOME/byz-fed-ids-5g/rev/runs/rev_"*"_5g" 2>/dev/null | head -n 1 || true)
[ -n "${RUN_DIR:-}" ] || { echo "ERROR: RUN_DIR introuvable"; exit 1; }

SUM_DIR="$RUN_DIR/summary"
[ -d "$SUM_DIR" ] || { echo "ERROR: summary dir introuvable: $SUM_DIR"; exit 1; }

TS=$(date -u +%Y%m%d_%H%M%S)
OUT_INV_CSV="$SUM_DIR/inventory_all_${TS}.csv"
OUT_INV_MD="$SUM_DIR/inventory_all_${TS}.md"
OUT_README="$RUN_DIR/README_${TS}.md"

ART_DIR="$RUN_DIR/artifacts_${TS}"
mkdir -p "$ART_DIR"

python3 - "$RUN_DIR" "$SUM_DIR" "$OUT_INV_CSV" "$OUT_INV_MD" "$OUT_README" "$ART_DIR" <<'PY'
import sys, json, csv, re, hashlib
from pathlib import Path

run_dir = Path(sys.argv[1])
sum_dir = Path(sys.argv[2])
out_csv = Path(sys.argv[3])
out_md  = Path(sys.argv[4])
out_readme = Path(sys.argv[5])
art_dir = Path(sys.argv[6])

def sha256_file(p: Path):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda: f.read(1024*1024), b''):
            h.update(b)
    return h.hexdigest()[:16]

def latest(pattern):
    files = sorted(sum_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0] if files else None

def safe_load_json(p):
    if not p or not p.exists(): return None
    return json.load(open(p))

def pick_metrics_baseline(d):
    if not isinstance(d, dict): return {}
    pooled = d.get("pooled_over_5rounds", {})
    return {
        "f1_avg": pooled.get("f1", {}).get("avg"),
        "fpr_avg": pooled.get("fpr", {}).get("avg"),
        "ipfs_p50": pooled.get("ipfs_ms", {}).get("p50"),
        "ipfs_p95": pooled.get("ipfs_ms", {}).get("p95"),
        "tx_p50": pooled.get("tx_ms", {}).get("p50"),
        "tx_p95": pooled.get("tx_ms", {}).get("p95"),
        "total_p50": pooled.get("total_ms", {}).get("p50"),
        "total_p95": pooled.get("total_ms", {}).get("p95"),
    }

def pick_metrics_attack(d):
    if not isinstance(d, dict): return {}
    pooled = d.get("pooled_over_5rounds", {})
    byz = pooled.get("pooled_byz", {})
    hon = pooled.get("pooled_honest", {})
    def m(x):
        return {"f1_avg": x.get("f1", {}).get("avg"), "fpr_avg": x.get("fpr", {}).get("avg")}
    return {"byz": m(byz), "honest": m(hon)}

# ---- detect key files (latest) ----
baseline_clean = latest("p7_baseline_5rounds_clean_*.json")
labelflip_clean = latest("p8_labelflip_5rounds_clean_*.json")
signflip_clean = latest("p10_signflip_5rounds_clean_*.json")

cmp_baseline_labelflip = latest("p9_compare_baseline_vs_labelflip_5rounds_*.json") or latest("p9_compare_baseline_vs_labelflip_5rounds_*.json")
cmp_baseline_signflip  = latest("p11_compare_baseline_vs_signflip_5rounds_*.json")

paper_labelflip_tex = latest("p9_paper_table_baseline_vs_labelflip_*.tex")
paper_labelflip_csv = latest("p9_paper_table_baseline_vs_labelflip_*.csv")
fig_labelflip_f1 = latest("p9_fig_f1_baseline_vs_labelflip_*.png")
fig_labelflip_fpr = latest("p9_fig_fpr_baseline_vs_labelflip_*.png")

paper_signflip_tex = latest("p11_paper_table_baseline_vs_signflip_*.tex")
paper_signflip_csv = latest("p11_paper_table_baseline_vs_signflip_*.csv")
fig_signflip_f1 = latest("p11_fig_f1_baseline_vs_signflip_*.png")
fig_signflip_fpr = latest("p11_fig_fpr_baseline_vs_signflip_*.png")

# ---- inventory all files in summary ----
rows=[]
for p in sorted(sum_dir.glob("*")):
    if p.is_dir(): 
        continue
    rows.append({
        "name": p.name,
        "type": p.suffix.lower().lstrip("."),
        "size_kb": round(p.stat().st_size/1024, 2),
        "sha16": sha256_file(p),
        "path": str(p),
    })

with out_csv.open("w", newline="") as f:
    w=csv.DictWriter(f, fieldnames=["name","type","size_kb","sha16","path"])
    w.writeheader()
    w.writerows(rows)

md=[]
md.append(f"# Inventory (summary) — {sum_dir.name}\n")
md.append(f"- RUN_DIR: `{run_dir}`")
md.append(f"- SUMMARY_DIR: `{sum_dir}`")
md.append(f"- Files: **{len(rows)}**\n")
md.append("| File | Type | Size (KB) | SHA256(16) |")
md.append("|---|---:|---:|---|")
for r in rows:
    md.append(f"| `{r['name']}` | {r['type']} | {r['size_kb']} | `{r['sha16']}` |")
out_md.write_text("\n".join(md) + "\n")

# ---- README content (short + actionable) ----
b = safe_load_json(baseline_clean)
lf = safe_load_json(labelflip_clean)
sf = safe_load_json(signflip_clean)

mb = pick_metrics_baseline(b)
mlf = pick_metrics_attack(lf)
msf = pick_metrics_attack(sf)

def fmt(x, nd=4):
    return "NA" if x is None else (f"{x:.{nd}f}" if isinstance(x,(int,float)) else str(x))

readme=[]
readme.append(f"# Experiment Artifacts — {run_dir.name}\n")
readme.append("This folder contains the experiment outputs (CSV/JSON/TEX/PNG) generated by the `rev/*.sh` scripts.\n")
readme.append("## Key inputs\n")
readme.append("- N clients: 20 (4 edge VMs)")
readme.append("- 5 rounds per scenario (baseline / label-flip / sign-flip)")
readme.append("- Fabric note: `FABRIC_ROUND` must be strictly increasing (rollback guard in chaincode).\n")
readme.append("## Results (pooled over 5 rounds)\n")
readme.append("### Baseline (all clients)\n")
readme.append(f"- F1 avg: **{fmt(mb.get('f1_avg'))}**")
readme.append(f"- FPR avg: **{fmt(mb.get('fpr_avg'))}**")
readme.append(f"- Latency total p50/p95 (ms): **{fmt(mb.get('total_p50'),2)} / {fmt(mb.get('total_p95'),2)}**")
readme.append(f"- Latency tx p50/p95 (ms): **{fmt(mb.get('tx_p50'),2)} / {fmt(mb.get('tx_p95'),2)}**")
readme.append(f"- Latency ipfs p50/p95 (ms): **{fmt(mb.get('ipfs_p50'),2)} / {fmt(mb.get('ipfs_p95'),2)}**\n")

if lf:
    readme.append("### Label-flip\n")
    readme.append(f"- Honest F1 avg: **{fmt(mlf['honest']['f1_avg'])}** | Honest FPR avg: **{fmt(mlf['honest']['fpr_avg'])}**")
    readme.append(f"- Byz F1 avg: **{fmt(mlf['byz']['f1_avg'])}** | Byz FPR avg: **{fmt(mlf['byz']['fpr_avg'])}**\n")
else:
    readme.append("### Label-flip\n- NA (file not found)\n")

if sf:
    readme.append("### Sign-flip\n")
    readme.append(f"- Honest F1 avg: **{fmt(msf['honest']['f1_avg'])}** | Honest FPR avg: **{fmt(msf['honest']['fpr_avg'])}**")
    readme.append(f"- Byz F1 avg: **{fmt(msf['byz']['f1_avg'])}** | Byz FPR avg: **{fmt(msf['byz']['fpr_avg'])}**\n")
else:
    readme.append("### Sign-flip\n- NA (file not found)\n")

readme.append("## Canonical pointers (latest)\n")
def add_ptr(label, p):
    if p and Path(p).exists():
        rel = Path(p).relative_to(run_dir)
        readme.append(f"- {label}: `{rel}`")
    else:
        readme.append(f"- {label}: NA")

add_ptr("Baseline clean JSON", baseline_clean)
add_ptr("Label-flip clean JSON", labelflip_clean)
add_ptr("Sign-flip clean JSON", signflip_clean)
add_ptr("Compare baseline vs label-flip (JSON)", cmp_baseline_labelflip)
add_ptr("Compare baseline vs sign-flip (JSON)", cmp_baseline_signflip)
add_ptr("Paper table baseline vs label-flip (CSV)", paper_labelflip_csv)
add_ptr("Paper table baseline vs label-flip (TEX)", paper_labelflip_tex)
add_ptr("Fig F1 baseline vs label-flip (PNG)", fig_labelflip_f1)
add_ptr("Fig FPR baseline vs label-flip (PNG)", fig_labelflip_fpr)
add_ptr("Paper table baseline vs sign-flip (CSV)", paper_signflip_csv)
add_ptr("Paper table baseline vs sign-flip (TEX)", paper_signflip_tex)
add_ptr("Fig F1 baseline vs sign-flip (PNG)", fig_signflip_f1)
add_ptr("Fig FPR baseline vs sign-flip (PNG)", fig_signflip_fpr)
readme.append("")
readme.append("## Inventory\n")
readme.append(f"- Full inventory CSV: `{out_csv.relative_to(run_dir)}`")
readme.append(f"- Full inventory MD: `{out_md.relative_to(run_dir)}`\n")

out_readme.write_text("\n".join(readme) + "\n")

# ---- bundle key artifacts into artifacts_* dir (copy + stable names) ----
def cp(src, dstname):
    if not src: 
        return
    src=Path(src)
    if not src.exists(): 
        return
    (art_dir / dstname).write_bytes(src.read_bytes())

cp(baseline_clean, "baseline_5rounds_clean.json")
cp(labelflip_clean, "labelflip_5rounds_clean.json")
cp(signflip_clean, "signflip_5rounds_clean.json")
cp(cmp_baseline_labelflip, "compare_baseline_vs_labelflip.json")
cp(cmp_baseline_signflip, "compare_baseline_vs_signflip.json")

cp(paper_labelflip_csv, "paper_table_baseline_vs_labelflip.csv")
cp(paper_labelflip_tex, "paper_table_baseline_vs_labelflip.tex")
cp(fig_labelflip_f1, "fig_f1_baseline_vs_labelflip.png")
cp(fig_labelflip_fpr, "fig_fpr_baseline_vs_labelflip.png")

cp(paper_signflip_csv, "paper_table_baseline_vs_signflip.csv")
cp(paper_signflip_tex, "paper_table_baseline_vs_signflip.tex")
cp(fig_signflip_f1, "fig_f1_baseline_vs_signflip.png")
cp(fig_signflip_fpr, "fig_fpr_baseline_vs_signflip.png")

# also include inventory + readme
cp(out_csv, out_csv.name)
cp(out_md, out_md.name)
cp(out_readme, out_readme.name)

print("OK")
print("RUN_DIR=", run_dir)
print("SUMMARY_DIR=", sum_dir)
print("INVENTORY_CSV=", out_csv)
print("INVENTORY_MD=", out_md)
print("README=", out_readme)
print("ARTIFACTS_DIR=", art_dir)
PY

TARBALL="$RUN_DIR/artifacts_${TS}.tar.gz"
tar -C "$RUN_DIR" -czf "$TARBALL" "$(basename "$ART_DIR")"

echo "OK"
echo "RUN_DIR= $RUN_DIR"
echo "INVENTORY_CSV= $OUT_INV_CSV"
echo "INVENTORY_MD= $OUT_INV_MD"
echo "README= $OUT_README"
echo "ARTIFACTS_DIR= $ART_DIR"
echo "TARBALL= $TARBALL"
